### ISSUE TITLE
MainMenu

### ISSUE THREAD

**Issue by fuzgirl1** [fuzgirl1/GeekyMath#1]
We really need to rewrite this. This part was written in the summer so the code itself cannot be used, but it doesn't mean that we can't redo it.

**Comment by Kitlu** [comment]
What if you rewrote it, since you would remember how you did it?

**Comment by fuzgirl1** [comment]
That's kinda the plan, just I want to use this kinda as a IRL walk-through for you all so you can get the hang of coding with Android stuffs

**Comment by Kitlu** [comment]
Alrighty!
