### ISSUE TITLE
PRESENTATION!!!!!!

### ISSUE THREAD

**Issue by jodale11** [fuzgirl1/GeekyMath#17]
I am going to upload the presentation to drive, hopefully by Tuesday, when do our presentation. We should see if we can ask Garcia to see if we could maybe take 5 minutes on Thursday to present

**Comment by fuzgirl1** [comment]
I swear this is my last update for tonight because I'm falling asleep at the keyboard, we ought to include the feedback about the app, maybe creating a post use survey that we could link into the app... No matter what, we need to talk about some more testing as it shows continued research.
