### ISSUE TITLE
Learn

### ISSUE THREAD

**Issue by fuzgirl1** [fuzgirl1/GeekyMath#2]
I have some notes that I will be posting on Drive for this that we need to finish up and post into an activity. I was thinking maybe a tabbed activity would make since.

**Comment by jodale11** [comment]
Oooooooookaaaaaaaaayyyyyyyyy.

**Comment by fuzgirl1** [comment]
Everyone really needs to start reading over this but the tough part is going to be reading as if you didn't understand binary. Please comment on that document as needed!

**Comment by fuzgirl1** [comment]
Right Now (first ignore all above I'm still trying to figure this out...) this is the most important thing to do! This is quite possibly the last thing that we really need to do for Regionals and we'll see from there!

**Comment by jodale11** [comment]
For this learn, could we do some like animation inside. So when we are done with one section, it clears the words and then brings out some new words.

**Comment by jodale11** [comment]
I was looking at the learn activity document, and I feel like there is some long portions that should be on one tab, but I know the tab is pretty small. So I feel like that is something we could do.

**Comment by Kitlu** [comment]
Animation would be nice. I guess it isn't too hard, we can do it.
I merged two of the sections; there's only 4 now. The Decimal System, Reading, Bases, and Finishing Up. I think it's good.

**Comment by fuzgirl1** [comment]
If someone is pretty good with photoshop/flash and making gifs/small projects, I would actually love some animation, especially for some of the examples.
