### ISSUE TITLE
Hexadecimal Feature

### ISSUE THREAD

**Issue by fuzgirl1** [fuzgirl1/GeekyMath#21]
Just tossing this out here if we still want to do this, adding a hexdecimal testing feature to start then maybe attempting to teach it. Just sayin' if we want to do this, we might want to have it unlockable instead of straight from the start.

**Comment by jodale11** [comment]
We also should need a Hexadecimal Learn.

**Comment by Kitlu** [comment]
I agree that we should have a Hexadecimal Learn; it's just weird to have a learn for Binary and not one for Hexadecimal.

Also, I like the idea of it being unlockable. That's cool.

**Comment by jodale11** [comment]
Just make it a sub-section of Learn.

**Comment by fuzgirl1** [comment]
What I was thinking for this is maybe we make it a set unlockable. Unlock hexadecimal test, unlock hexadecimal learn.

**Comment by fuzgirl1** [comment]
So with state coming so soon, maybe we should focus first on binary, then get along to this. Hexadecimal learn is going to be really hard to write too.

**Comment by fuzgirl1** [comment]
Okay so I've got the keyboard working by itself, but I'm struggling to integrate it into the app (or I just can't think straight while I'm falling asleep). I think I've got the hex test going, idk I can't test it without the keyboard so...
