### ISSUE TITLE
Answer Me!!!!

### ISSUE THREAD

**Issue by jodale11** [fuzgirl1/GeekyMath#24]
We have an awkward loop. INFINITE LOOP.

**Comment by fuzgirl1** [comment]
Okay, that's one way to describe the issue... Anyway, I think I know of a way to fix it, but I need someone to logic check me and see if this makes any sense. I'll draw it on the dry erase board tomorrow.

**Comment by fuzgirl1** [comment]
This is now done, but I want us to do a thorough testing of this incase there is something wrong with it. I already uploaded the current update on here (although I'm not sure if its come through) and it is on our devices.
