### ISSUE TITLE
"Scientific Experiment"

### ISSUE THREAD

**Issue by jodale11** [fuzgirl1/GeekyMath#26]
So I finally posted on Facebook to see how many people would be willing to "experiment" with the App. What I am thinking also while I am typing this, is could we get disqualified if we deliver it to Google Play Store? If not, then I would like to see if we can upload it to Play Store this week.

**Comment by fuzgirl1** [comment]
I've been thinking about the same thing recently with the Google Play Store. I'm going to ask Garcia tomorrow to see if he has a clue about it, if not then I might fire another quick email to the coordinator and manager for the event. But we even have to be careful about giving to too many people, I want people that have the app to check with us about once a week so they can update on how it's working.

**Comment by fuzgirl1** [comment]
Okay, so I asked Garcia and he wasn't sure if we could or not. He really didn't see a reason not to, but I sent the coordinator and manager an email just in case. Currently I'm waiting for a response, but we'll see if we can, if so I'll go ahead and make us official google play store developers.
