### ISSUE TITLE
Binder

### ISSUE THREAD

**Issue by fuzgirl1** [fuzgirl1/GeekyMath#8]
In the binder, we're going to need:
1. Title Page
2. Table of Contents
3. Research
4. Description, including problem, solution, and social or educational value.
5. Plan of Work
6. Documentation
   a. Project Requirements
   b. High-level Software Design
   c. Testing
   d. End-user Product Documents
7. Team's Evaluation and Project's Future
8. List of References
9. CD/DVD
   a. Multimedia Presentation
   b. Project Source Code
   c. Runnable, compiled program

And sadly, the Portfolio will not be returned after the event, at least at Nationals I'm not sure how it will be handled at Regionals,

**Comment by jodale11** [comment]
That means we are going to need 1-3 different types of binders, depending on how we placed.

**Comment by Kitlu** [comment]
Cool, thanks. I'm down for working on this.
